<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

?>
<?php
/**
 * Template for displaying category list widget
 *
 * @var $block \MageKey\CategoryListWidget\Block\Widget
 */
if ($categoryNode = $block->getCategoryNode()) {
    $title = $block->getTitle();
    $_decorator = $this->helper(\MageKey\CategoryListWidget\Helper\Decorator::class);
}
?>
<?php if ($categoryNode) : ?>
<div class="block widget mgk-category-list-widget">
    <?php if ($title) : ?>
    <div class="block-title">
        <strong role="heading" aria-level="2"><?= $block->escapeHtml($title) ?></strong>
    </div>
    <?php endif; ?>
    <div class="block-content <?= /* @escapeNotVerified */ $_decorator->renderWrapperClass($categoryNode) ?>">
        <?= /* @escapeNotVerified */ $block->getNodeRenderer()->setNode($categoryNode)->toHtml() ?>
    </div>
</div>
<?php endif; ?>
