<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

?>
<?php
/**
 * Template for displaying category list node
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

if (($node = $block->getNode()) && $node->hasChildren()) {
    $exists = true;
    $level = (int)$block->getLevel();
    $cssClass = !$level ? 'default collapsible' : '';
    $isCollapsible = !$level;
}
?>
<?php if (isset($exists)) : ?>
    <ul class="items <?= /* @escapeNotVerified */ $cssClass ?>">
        <?php foreach ($node->getChildren() as $child) : ?>
        <li <?php if ($isCollapsible) : ?>
            class="item collapsible"
            data-mage-init='{
                "collapsible":{
                    "openedState": "active"
                }
            }'
            <?php else : ?>
            class="item"
            <?php endif; ?>>
            <a href="<?= /* @escapeNotVerified */ $child->getUrl() ?>" data-role="title">
                <?= /* @escapeNotVerified */ $child->getName() ?>
            </a>
            <div class="items-container" data-role="content">
                <?= /* @escapeNotVerified */ $block->setNode($child)->setLevel($level + 1)->toHtml() ?>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
