<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

?>
<?php
/**
 * Template for displaying category list node
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

if (($node = $block->getNode()) && $node->hasChildren()) {
    $exists = true;
    $level = (int)$node->getClwLevel();
    $_decorator = $this->helper(\MageKey\CategoryListWidget\Helper\Decorator::class);
}
?>
<?php if (isset($exists)) : ?>
    <ul <?= /* @escapeNotVerified */ $_decorator->renderAttributes($node, ['list']) ?>>
        <?php foreach ($node->getChildren() as $child) : ?>
            <?php $child->setClwLevel($level + 1); ?>
            <li <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['item']) ?>>
                <a <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['link']) ?>
                   href="<?= /* @escapeNotVerified */ $child->getUrl() ?>">
                    <?= /* @escapeNotVerified */ $child->getName() ?>
                </a>
                <?= /* @escapeNotVerified */ $block->setNode($child)->toHtml() ?>
            </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
