<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

?>
<?php
/**
 * Template for displaying category list node
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

if (($node = $block->getNode()) && $node->hasChildren()) {
    $exists = true;
    $level = (int)$node->getClwLevel();

    $options = $block->getOptions();
    $imageAttribute = $options->getData('image_attribute') ?: 'image';
    $columnsCount = (int)$options->getData('columns_count');
    $viewButton = (string)$options->getData('view_button');

    $_imageHelper = $this->helper(\MageKey\CategoryListWidget\Helper\Image::class);
    $image = 'mgk_categorylistwidget_inline_images';
    $mediaAttributes = $_imageHelper->getMediaAttributes($image);
    $imageAttr = [
        'width' => $options->getData('image_width') ?: $mediaAttributes['width'],
        'height' => $options->getData('image_height') ?: $mediaAttributes['height'],
    ];
    $imageStyle = 'width:' . $imageAttr['width'] . 'px;';
    $imageStyle .= 'height:' . $imageAttr['height'] . 'px;';

    $_decorator = $this->helper(\MageKey\CategoryListWidget\Helper\Decorator::class);
}
?>
<?php if (isset($exists)) : ?>
    <?php if (!$level) : ?>
    <ul <?= /* @escapeNotVerified */ $_decorator->renderAttributes($node, ['list', 'columns-' . $columnsCount]) ?>>
    <?php endif; ?>
        <?php foreach ($node->getChildren() as $child) : ?>
            <?php $child->setClwLevel($level + 1); ?>
            <li <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['item']) ?>>
                <div <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['container']) ?>>
                    <a <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['link']) ?>
                       href="<?= /* @escapeNotVerified */ $child->getUrl() ?>">
                        <div <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['image']) ?>
                             style="<?= /* @escapeNotVerified */ $imageStyle ?>">
                            <img alt="<?= /* @escapeNotVerified */ $child->getName() ?>"
                                 src="<?= /* @escapeNotVerified */ $_imageHelper->getImage('catalog/category/' . $child->getData($imageAttribute), $image, $imageAttr) ?>" />
                        </div>
                        <div <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['name']) ?>><?= /* @escapeNotVerified */ $child->getName() ?></div>
                    </a>
                    <?php if ($viewButton) : ?>
                    <div <?= /* @escapeNotVerified */ $_decorator->renderAttributes($child, ['actions']) ?>>
                        <a class="action primary <?= /* @escapeNotVerified */ $_decorator->renderClass($child, ['action']) ?>"
                           href="<?= /* @escapeNotVerified */ $child->getUrl() ?>">
                            <?= /* @escapeNotVerified */ __($viewButton) ?>
                        </a>
                    </div>
                    <?php endif; ?>
                </div>
            </li>
            <?= /* @escapeNotVerified */ $block->setNode($child)->toHtml() ?>
        <?php endforeach; ?>
    <?php if (!$level) : ?>
    </ul>
    <?php endif; ?>
<?php endif; ?>
