<?php
/**
 * Copyright © MageKey. All rights reserved.
 * See LICENSE.txt for license details.
 */

?>
<?php
/**
 * Template for displaying category list node
 *
 * @var $block \Magento\Framework\View\Element\Template
 */

if (($node = $block->getNode()) && $node->hasChildren()) {
    $exists = true;
    $level = (int)$block->getLevel();
    $options = $block->getOptions();
    $imageAttribute = $options->getData('image_attribute') ?: 'image';
    $columnsCount = (int)$options->getData('columns_count');
    $cssClass = !$level ? ' inline-images nested columns-' . $columnsCount : '';
    $_imageHelper = $this->helper(\MageKey\CategoryListWidget\Helper\Image::class);
    $image = 'mgk_categorylistwidget_inline_images';
    $mediaAttributes = $_imageHelper->getMediaAttributes($image);
    $imageAttr = [
        'width' => $options->getData('image_width') ?: $mediaAttributes['width'],
        'height' => $options->getData('image_height') ?: $mediaAttributes['height'],
    ];
    $catImageStyle = 'width:' . $imageAttr['width'] . 'px;';
    $catImageStyle .= 'height:' . $imageAttr['height'] . 'px;';
}
?>
<?php if (isset($exists)) : ?>    
    <ul class="items<?= /* @escapeNotVerified */ $cssClass ?>">
        <?php foreach ($node->getChildren() as $child) : ?>
        <li class="item">
            <div class="item-container">
                <?php if (!$level) : ?>
                <a class="item-link" href="<?= /* @escapeNotVerified */ $child->getUrl() ?>">
                    <div class="item-image" style="<?= /* @escapeNotVerified */ $catImageStyle ?>">
                        <img alt="<?= /* @escapeNotVerified */ $child->getName() ?>"
                            src="<?= /* @escapeNotVerified */ $_imageHelper->getImage('catalog/category/' . $child->getData($imageAttribute), $image, $imageAttr) ?>" />
                    </div>
                    <div class="item-name"><?= /* @escapeNotVerified */ $child->getName() ?></div>
                </a>
                <?php else : ?>
                <a href="<?= /* @escapeNotVerified */ $child->getUrl() ?>">
                    <?= /* @escapeNotVerified */ $child->getName() ?>
                </a>
                <?php endif; ?>
                <?= /* @escapeNotVerified */ $block->setNode($child)->setLevel($level + 1)->toHtml() ?>
            </div>
        </li>
        <?php endforeach; ?>
    </ul>
<?php endif; ?>
